; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.50727.1 

	TITLE	C:\Users\lw8172\Documents\GitHub\HookTestBed\WDMDriverTest\WDMDriverTest\HookHelper.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?g_FunNtCreateProcess@@3P6GJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@ZA ; g_FunNtCreateProcess
PUBLIC	?NtCreateProcessOriginalBytes@@3PAEA		; NtCreateProcessOriginalBytes
PUBLIC	?ObReferenceObjectByHandleOriginalBytes@@3PAEA	; ObReferenceObjectByHandleOriginalBytes
_BSS	SEGMENT
?g_FunNtCreateProcess@@3P6GJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@ZA DD 01H DUP (?) ; g_FunNtCreateProcess
?NtCreateProcessOriginalBytes@@3PAEA DB 05H DUP (?)	; NtCreateProcessOriginalBytes
	ALIGN	4

?ObReferenceObjectByHandleOriginalBytes@@3PAEA DB 05H DUP (?) ; ObReferenceObjectByHandleOriginalBytes
_BSS	ENDS
PUBLIC	??3@YAXPAX@Z					; operator delete
PUBLIC	??0HookHelper@@QAE@XZ				; HookHelper::HookHelper
PUBLIC	??1HookHelper@@QAE@XZ				; HookHelper::~HookHelper
PUBLIC	?HookObReferenceObjectByHandle@HookHelper@@QAEEPAPAX@Z ; HookHelper::HookObReferenceObjectByHandle
PUBLIC	?UnHookObReferenceObjectByHandle@HookHelper@@QAEEXZ ; HookHelper::UnHookObReferenceObjectByHandle
PUBLIC	?HookNtCreateProcess@HookHelper@@QAEEPAPAX@Z	; HookHelper::HookNtCreateProcess
PUBLIC	?UnHookNtCreateProcess@HookHelper@@QAEEXZ	; HookHelper::UnHookNtCreateProcess
PUBLIC	?FindSpeCodeInMemory@HookHelper@@QAEJPAK0K@Z	; HookHelper::FindSpeCodeInMemory
PUBLIC	?PageOn@@YGXXZ					; PageOn
PUBLIC	?PageOff@@YGXXZ					; PageOff
PUBLIC	?FindSubString@@YGEPAU_UNICODE_STRING@@0@Z	; FindSubString
PUBLIC	?OriginalObReferenceObjectByHandle@@YGJPAXKPAU_OBJECT_TYPE@@DPAPAXPAU_OBJECT_HANDLE_INFORMATION@@@Z ; OriginalObReferenceObjectByHandle
PUBLIC	?NewObReferenceObjectByHandle@@YGJPAXKPAU_OBJECT_TYPE@@DPAPAXPAU_OBJECT_HANDLE_INFORMATION@@@Z ; NewObReferenceObjectByHandle
PUBLIC	?OriginalNewNtCreateProcessEx@@YGJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@Z ; OriginalNewNtCreateProcessEx
PUBLIC	?NewNtCreateProcessEx@@YGJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@Z ; NewNtCreateProcessEx
PUBLIC	??_C@_0BN@NDKJECNL@NewObReferenceObjectByHandle?$AA@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0BI@IHKBDNEF@?$FL?$CFs?$FN?5?0?5ProcessName?3?5?$CFs?6?$AA@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0M@ENKGKOKC@notepad?4exe?$AA@FNODOBFM@	;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0BF@LFKNIPGB@NewNtCreateProcessEx?$AA@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0DC@OIAGNPLD@?$FL?$CFs?$FN?5?$DM?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?6?5Im@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_1BI@JANGOEPN@?$AAN?$AAO?$AAT?$AAE?$AAP?$AAA?$AAD?$AA?4?$AAE?$AAX?$AAE?$AA?$AA@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0BJ@FPHAFKAG@?$FL?$CFs?$FN?5IS?5NOTEPAD?4EXE?$CB?$CB?5?5?6?$AA@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0BH@OKKHHBGM@HookHelper?3?3HookHelper?$AA@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0BO@MNJPLLPD@?$FL?$CFs?$FN?5?$DM?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?6?$AA@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0BI@HFJKMNDA@HookHelper?3?3?$HOHookHelper?$AA@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0CK@EMEBBEAG@HookHelper?3?3HookObReferenceObjec@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0CC@GLBJJFCJ@?$FLObReferenceObjectByHandle?$FN?5?30x?$CF@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0BO@HKHHGHLB@?$FL?$CFs?$FN?5?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?$DO?5?6?$AA@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0CM@HAAJIBHO@HookHelper?3?3UnHookObReferenceObj@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0CA@DDCEFIIE@HookHelper?3?3HookNtCreateProcess?$AA@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_1CI@PBJJPAEM@?$AAN?$AAt?$AAC?$AAr?$AAe?$AAa?$AAt?$AAe?$AAU?$AAs?$AAe?$AAr?$AAP?$AAr?$AAo?$AAc?$AAe?$AAs?$AAs?$AA?$AA@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0CJ@IPJOHLF@?$FL?$CFs?$FN?5g_FunNtCreateProcess?5?$DN?$DN?5NUL@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0BI@CHNNDCKM@?$FLNtCreateProcess?$FN?5?30x?$CFx?$AA@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0CC@EKOPFHFD@HookHelper?3?3UnHookNtCreateProces@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0CA@GHBGDHMM@HookHelper?3?3FindSpeCodeInMemory?$AA@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0CC@BKIIOGJF@?$FL?$CFs?$FN?5failed?5alloc?5memory?5failed?5@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0BC@OBFBDDCK@?$FL?$CFs?$FN?5uSzie?5?$DN?5?$CFd?5?6?$AA@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0BE@BMFCHCEB@?$FL?$CFs?$FN?5failed?5query?5?6?$AA@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0CI@PDKKEKCF@?$FL?$CFs?$FN?5Base?3?$CF08x?0?5End?3?$CF08x?5ImageNa@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0BA@EGNDBCFN@?$FL?$CFs?$FN?5Find?3?$CF08x?6?$AA@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
PUBLIC	??_C@_0BA@FFJEGKCA@?$FL?$CFs?$FN?5UnFind?5?4?5?6?$AA@FNODOBFM@ ;  ?? ::FNODOBFM::`string'
EXTRN	__stricmp:PROC
EXTRN	__wcsnicmp:PROC
EXTRN	__imp__RtlInitUnicodeString@8:PROC
EXTRN	__imp__RtlEqualUnicodeString@12:PROC
EXTRN	_DbgPrint:PROC
EXTRN	__imp_@KfLowerIrql@4:PROC
EXTRN	__imp_@KfRaiseIrql@4:PROC
EXTRN	__imp__KeGetCurrentIrql@0:PROC
EXTRN	__imp__ExAllocatePool@8:PROC
EXTRN	__imp__ExFreePool@4:PROC
EXTRN	__imp__ObReferenceObjectByHandle@24:PROC
EXTRN	__imp__ZwQuerySystemInformation@16:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	_PsProcessType:DWORD
EXTRN	___security_cookie:DWORD
;	COMDAT ??_C@_0BA@FFJEGKCA@?$FL?$CFs?$FN?5UnFind?5?4?5?6?$AA@FNODOBFM@
text$s	SEGMENT
??_C@_0BA@FFJEGKCA@?$FL?$CFs?$FN?5UnFind?5?4?5?6?$AA@FNODOBFM@ DB '[%s] U'
	DB	'nFind . ', 0aH, 00H				;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0BA@EGNDBCFN@?$FL?$CFs?$FN?5Find?3?$CF08x?6?$AA@FNODOBFM@
text$s	SEGMENT
??_C@_0BA@EGNDBCFN@?$FL?$CFs?$FN?5Find?3?$CF08x?6?$AA@FNODOBFM@ DB '[%s] '
	DB	'Find:%08x', 0aH, 00H			;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0CI@PDKKEKCF@?$FL?$CFs?$FN?5Base?3?$CF08x?0?5End?3?$CF08x?5ImageNa@FNODOBFM@
text$s	SEGMENT
??_C@_0CI@PDKKEKCF@?$FL?$CFs?$FN?5Base?3?$CF08x?0?5End?3?$CF08x?5ImageNa@FNODOBFM@ DB '['
	DB	'%s] Base:%08x, End:%08x ImageName:%s ', 0aH, 00H ;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0BE@BMFCHCEB@?$FL?$CFs?$FN?5failed?5query?5?6?$AA@FNODOBFM@
text$s	SEGMENT
??_C@_0BE@BMFCHCEB@?$FL?$CFs?$FN?5failed?5query?5?6?$AA@FNODOBFM@ DB '[%s'
	DB	'] failed query ', 0aH, 00H			;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0BC@OBFBDDCK@?$FL?$CFs?$FN?5uSzie?5?$DN?5?$CFd?5?6?$AA@FNODOBFM@
text$s	SEGMENT
??_C@_0BC@OBFBDDCK@?$FL?$CFs?$FN?5uSzie?5?$DN?5?$CFd?5?6?$AA@FNODOBFM@ DB '['
	DB	'%s] uSzie = %d ', 0aH, 00H			;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0CC@BKIIOGJF@?$FL?$CFs?$FN?5failed?5alloc?5memory?5failed?5@FNODOBFM@
text$s	SEGMENT
??_C@_0CC@BKIIOGJF@?$FL?$CFs?$FN?5failed?5alloc?5memory?5failed?5@FNODOBFM@ DB '['
	DB	'%s] failed alloc memory failed ', 0aH, 00H	;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0CA@GHBGDHMM@HookHelper?3?3FindSpeCodeInMemory?$AA@FNODOBFM@
text$s	SEGMENT
??_C@_0CA@GHBGDHMM@HookHelper?3?3FindSpeCodeInMemory?$AA@FNODOBFM@ DB 'Ho'
	DB	'okHelper::FindSpeCodeInMemory', 00H		;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0CC@EKOPFHFD@HookHelper?3?3UnHookNtCreateProces@FNODOBFM@
text$s	SEGMENT
??_C@_0CC@EKOPFHFD@HookHelper?3?3UnHookNtCreateProces@FNODOBFM@ DB 'HookH'
	DB	'elper::UnHookNtCreateProcess', 00H		;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0BI@CHNNDCKM@?$FLNtCreateProcess?$FN?5?30x?$CFx?$AA@FNODOBFM@
text$s	SEGMENT
??_C@_0BI@CHNNDCKM@?$FLNtCreateProcess?$FN?5?30x?$CFx?$AA@FNODOBFM@ DB '['
	DB	'NtCreateProcess] :0x%x', 00H		;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0CJ@IPJOHLF@?$FL?$CFs?$FN?5g_FunNtCreateProcess?5?$DN?$DN?5NUL@FNODOBFM@
text$s	SEGMENT
??_C@_0CJ@IPJOHLF@?$FL?$CFs?$FN?5g_FunNtCreateProcess?5?$DN?$DN?5NUL@FNODOBFM@ DB '['
	DB	'%s] g_FunNtCreateProcess == NULL !!!!!', 0aH, 00H ;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_1CI@PBJJPAEM@?$AAN?$AAt?$AAC?$AAr?$AAe?$AAa?$AAt?$AAe?$AAU?$AAs?$AAe?$AAr?$AAP?$AAr?$AAo?$AAc?$AAe?$AAs?$AAs?$AA?$AA@FNODOBFM@
text$s	SEGMENT
??_C@_1CI@PBJJPAEM@?$AAN?$AAt?$AAC?$AAr?$AAe?$AAa?$AAt?$AAe?$AAU?$AAs?$AAe?$AAr?$AAP?$AAr?$AAo?$AAc?$AAe?$AAs?$AAs?$AA?$AA@FNODOBFM@ DB 'N'
	DB	00H, 't', 00H, 'C', 00H, 'r', 00H, 'e', 00H, 'a', 00H, 't', 00H
	DB	'e', 00H, 'U', 00H, 's', 00H, 'e', 00H, 'r', 00H, 'P', 00H, 'r'
	DB	00H, 'o', 00H, 'c', 00H, 'e', 00H, 's', 00H, 's', 00H, 00H, 00H ;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0CA@DDCEFIIE@HookHelper?3?3HookNtCreateProcess?$AA@FNODOBFM@
text$s	SEGMENT
??_C@_0CA@DDCEFIIE@HookHelper?3?3HookNtCreateProcess?$AA@FNODOBFM@ DB 'Ho'
	DB	'okHelper::HookNtCreateProcess', 00H		;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0CM@HAAJIBHO@HookHelper?3?3UnHookObReferenceObj@FNODOBFM@
text$s	SEGMENT
??_C@_0CM@HAAJIBHO@HookHelper?3?3UnHookObReferenceObj@FNODOBFM@ DB 'HookH'
	DB	'elper::UnHookObReferenceObjectByHandle', 00H ;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0BO@HKHHGHLB@?$FL?$CFs?$FN?5?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?$DO?5?6?$AA@FNODOBFM@
text$s	SEGMENT
??_C@_0BO@HKHHGHLB@?$FL?$CFs?$FN?5?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?$DO?5?6?$AA@FNODOBFM@ DB '['
	DB	'%s] ---------------------> ', 0aH, 00H	;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0CC@GLBJJFCJ@?$FLObReferenceObjectByHandle?$FN?5?30x?$CF@FNODOBFM@
text$s	SEGMENT
??_C@_0CC@GLBJJFCJ@?$FLObReferenceObjectByHandle?$FN?5?30x?$CF@FNODOBFM@ DB '['
	DB	'ObReferenceObjectByHandle] :0x%x', 00H	;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0CK@EMEBBEAG@HookHelper?3?3HookObReferenceObjec@FNODOBFM@
text$s	SEGMENT
??_C@_0CK@EMEBBEAG@HookHelper?3?3HookObReferenceObjec@FNODOBFM@ DB 'HookH'
	DB	'elper::HookObReferenceObjectByHandle', 00H	;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0BI@HFJKMNDA@HookHelper?3?3?$HOHookHelper?$AA@FNODOBFM@
text$s	SEGMENT
??_C@_0BI@HFJKMNDA@HookHelper?3?3?$HOHookHelper?$AA@FNODOBFM@ DB 'HookHel'
	DB	'per::~HookHelper', 00H			;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0BO@MNJPLLPD@?$FL?$CFs?$FN?5?$DM?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?6?$AA@FNODOBFM@
text$s	SEGMENT
??_C@_0BO@MNJPLLPD@?$FL?$CFs?$FN?5?$DM?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?6?$AA@FNODOBFM@ DB '['
	DB	'%s] <----------------------', 0aH, 00H	;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0BH@OKKHHBGM@HookHelper?3?3HookHelper?$AA@FNODOBFM@
text$s	SEGMENT
??_C@_0BH@OKKHHBGM@HookHelper?3?3HookHelper?$AA@FNODOBFM@ DB 'HookHelper:'
	DB	':HookHelper', 00H				;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0BJ@FPHAFKAG@?$FL?$CFs?$FN?5IS?5NOTEPAD?4EXE?$CB?$CB?5?5?6?$AA@FNODOBFM@
text$s	SEGMENT
??_C@_0BJ@FPHAFKAG@?$FL?$CFs?$FN?5IS?5NOTEPAD?4EXE?$CB?$CB?5?5?6?$AA@FNODOBFM@ DB '['
	DB	'%s] IS NOTEPAD.EXE!!  ', 0aH, 00H		;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_1BI@JANGOEPN@?$AAN?$AAO?$AAT?$AAE?$AAP?$AAA?$AAD?$AA?4?$AAE?$AAX?$AAE?$AA?$AA@FNODOBFM@
text$s	SEGMENT
??_C@_1BI@JANGOEPN@?$AAN?$AAO?$AAT?$AAE?$AAP?$AAA?$AAD?$AA?4?$AAE?$AAX?$AAE?$AA?$AA@FNODOBFM@ DB 'N'
	DB	00H, 'O', 00H, 'T', 00H, 'E', 00H, 'P', 00H, 'A', 00H, 'D', 00H
	DB	'.', 00H, 'E', 00H, 'X', 00H, 'E', 00H, 00H, 00H ;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0DC@OIAGNPLD@?$FL?$CFs?$FN?5?$DM?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?6?5Im@FNODOBFM@
text$s	SEGMENT
??_C@_0DC@OIAGNPLD@?$FL?$CFs?$FN?5?$DM?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?6?5Im@FNODOBFM@ DB '['
	DB	'%s] <----------------------', 0aH, ' ImageName:[%wZ],  ', 0aH
	DB	00H						;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0BF@LFKNIPGB@NewNtCreateProcessEx?$AA@FNODOBFM@
text$s	SEGMENT
??_C@_0BF@LFKNIPGB@NewNtCreateProcessEx?$AA@FNODOBFM@ DB 'NewNtCreateProc'
	DB	'essEx', 00H					;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0M@ENKGKOKC@notepad?4exe?$AA@FNODOBFM@
text$s	SEGMENT
??_C@_0M@ENKGKOKC@notepad?4exe?$AA@FNODOBFM@ DB 'notepad.exe', 00H ;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0BI@IHKBDNEF@?$FL?$CFs?$FN?5?0?5ProcessName?3?5?$CFs?6?$AA@FNODOBFM@
text$s	SEGMENT
??_C@_0BI@IHKBDNEF@?$FL?$CFs?$FN?5?0?5ProcessName?3?5?$CFs?6?$AA@FNODOBFM@ DB '['
	DB	'%s] , ProcessName: %s', 0aH, 00H		;  ?? ::FNODOBFM::`string'
text$s	ENDS
;	COMDAT ??_C@_0BN@NDKJECNL@NewObReferenceObjectByHandle?$AA@FNODOBFM@
text$s	SEGMENT
??_C@_0BN@NDKJECNL@NewObReferenceObjectByHandle?$AA@FNODOBFM@ DB 'NewObRe'
	DB	'ferenceObjectByHandle', 00H			;  ?? ::FNODOBFM::`string'
text$s	ENDS
; Function compile flags: /Odtp
; File c:\users\lw8172\documents\github\hooktestbed\wdmdrivertest\wdmdrivertest\hookhelper.cpp
;	COMDAT ?NewNtCreateProcessEx@@YGJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@Z
_TEXT	SEGMENT
_strNotePad$ = -12					; size = 8
_status$ = -4						; size = 4
_ProcessHandle$ = 8					; size = 4
_ThreadHandle$ = 12					; size = 4
_Parameter2$ = 16					; size = 4
_Parameter3$ = 20					; size = 4
_ProcessSecurityDescriptor$ = 24			; size = 4
_ThreadSecurityDescriptor$ = 28				; size = 4
_Parameter6$ = 32					; size = 4
_Parameter7$ = 36					; size = 4
_ProcessParameters$ = 40				; size = 4
_Parameter9$ = 44					; size = 4
_pProcessUnKnow$ = 48					; size = 4
?NewNtCreateProcessEx@@YGJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@Z PROC ; NewNtCreateProcessEx, COMDAT

; 140  : {

	npad	2
	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH

; 141  : 	KdPrint(("[%s] <----------------------\n ImageName:[%wZ],  \n", __FUNCTION__, &(ProcessParameters->ImagePathName)));  

	mov	eax, DWORD PTR _ProcessParameters$[ebp]
	add	eax, 56					; 00000038H
	push	eax
	push	OFFSET ??_C@_0BF@LFKNIPGB@NewNtCreateProcessEx?$AA@FNODOBFM@
	push	OFFSET ??_C@_0DC@OIAGNPLD@?$FL?$CFs?$FN?5?$DM?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?6?5Im@FNODOBFM@
	call	_DbgPrint
	add	esp, 12					; 0000000cH

; 142  : 	NTSTATUS status = STATUS_SUCCESS;

	mov	DWORD PTR _status$[ebp], 0

; 143  : 	UNICODE_STRING strNotePad;
; 144  : 
; 145  : 	RtlInitUnicodeString(&strNotePad, L"NOTEPAD.EXE");

	push	OFFSET ??_C@_1BI@JANGOEPN@?$AAN?$AAO?$AAT?$AAE?$AAP?$AAA?$AAD?$AA?4?$AAE?$AAX?$AAE?$AA?$AA@FNODOBFM@
	lea	ecx, DWORD PTR _strNotePad$[ebp]
	push	ecx
	call	DWORD PTR __imp__RtlInitUnicodeString@8

; 146  : 
; 147  : 	if (FindSubString(&(ProcessParameters->ImagePathName),&(strNotePad)))

	lea	edx, DWORD PTR _strNotePad$[ebp]
	push	edx
	mov	eax, DWORD PTR _ProcessParameters$[ebp]
	add	eax, 56					; 00000038H
	push	eax
	call	?FindSubString@@YGEPAU_UNICODE_STRING@@0@Z ; FindSubString
	movzx	ecx, al
	test	ecx, ecx
	je	SHORT $LN2@NewNtCreat

; 148  : 	{
; 149  : 		KdPrint(("[%s] IS NOTEPAD.EXE!!  \n", __FUNCTION__));  

	push	OFFSET ??_C@_0BF@LFKNIPGB@NewNtCreateProcessEx?$AA@FNODOBFM@
	push	OFFSET ??_C@_0BJ@FPHAFKAG@?$FL?$CFs?$FN?5IS?5NOTEPAD?4EXE?$CB?$CB?5?5?6?$AA@FNODOBFM@
	call	_DbgPrint
	add	esp, 8

; 150  : 		return STATUS_ACCESS_DENIED;

	mov	eax, -1073741790			; c0000022H
	jmp	SHORT $LN3@NewNtCreat
$LN2@NewNtCreat:

; 151  : 	}
; 152  : 
; 153  : 	status = OriginalNewNtCreateProcessEx(ProcessHandle,
; 154  : 		ThreadHandle,
; 155  : 		Parameter2,
; 156  : 		Parameter3,
; 157  : 		ProcessSecurityDescriptor,
; 158  : 		ThreadSecurityDescriptor,
; 159  : 		Parameter6,
; 160  : 		Parameter7,
; 161  : 		ProcessParameters,
; 162  : 		Parameter9,
; 163  : 		pProcessUnKnow
; 164  : 		);

	mov	edx, DWORD PTR _pProcessUnKnow$[ebp]
	push	edx
	mov	eax, DWORD PTR _Parameter9$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ProcessParameters$[ebp]
	push	ecx
	mov	edx, DWORD PTR _Parameter7$[ebp]
	push	edx
	mov	eax, DWORD PTR _Parameter6$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ThreadSecurityDescriptor$[ebp]
	push	ecx
	mov	edx, DWORD PTR _ProcessSecurityDescriptor$[ebp]
	push	edx
	mov	eax, DWORD PTR _Parameter3$[ebp]
	push	eax
	mov	ecx, DWORD PTR _Parameter2$[ebp]
	push	ecx
	mov	edx, DWORD PTR _ThreadHandle$[ebp]
	push	edx
	mov	eax, DWORD PTR _ProcessHandle$[ebp]
	push	eax
	call	?OriginalNewNtCreateProcessEx@@YGJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@Z ; OriginalNewNtCreateProcessEx
	mov	DWORD PTR _status$[ebp], eax

; 165  : 
; 166  : 	if (NT_SUCCESS(status))
; 167  : 	{
; 168  : 		//KdPrint(("[%s] , ProcessName: %s\n", __FUNCTION__, (char *)((ULONG)(*ProcessHandle) + EPROCESS_NAME_OFFSET)));  
; 169  : 	}
; 170  : 
; 171  : 	return status;

	mov	eax, DWORD PTR _status$[ebp]
$LN3@NewNtCreat:

; 172  : }

	mov	esp, ebp
	pop	ebp
	ret	44					; 0000002cH
?NewNtCreateProcessEx@@YGJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@Z ENDP ; NewNtCreateProcessEx
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\lw8172\documents\github\hooktestbed\wdmdrivertest\wdmdrivertest\hookhelper.cpp
;	COMDAT ?OriginalNewNtCreateProcessEx@@YGJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@Z
_TEXT	SEGMENT
_ProcessHandle$ = 8					; size = 4
_ThreadHandle$ = 12					; size = 4
_Parameter2$ = 16					; size = 4
_Parameter3$ = 20					; size = 4
_ProcessSecurityDescriptor$ = 24			; size = 4
_ThreadSecurityDescriptor$ = 28				; size = 4
_Parameter6$ = 32					; size = 4
_Parameter7$ = 36					; size = 4
_ProcessParameters$ = 40				; size = 4
_Parameter9$ = 44					; size = 4
_pProcessUnKnow$ = 48					; size = 4
?OriginalNewNtCreateProcessEx@@YGJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@Z PROC ; OriginalNewNtCreateProcessEx, COMDAT

; 112  : #ifdef _X86_
; 113  : 	_asm     
; 114  : 	{         
; 115  : 		push 6B8h

	push	1720					; 000006b8H

; 116  : 		mov eax,g_FunNtCreateProcess

	mov	eax, DWORD PTR ?g_FunNtCreateProcess@@3P6GJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@ZA ; g_FunNtCreateProcess

; 117  : 		add eax,5

	add	eax, 5

; 118  : 		jmp eax                      

	jmp	eax
?OriginalNewNtCreateProcessEx@@YGJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@Z ENDP ; OriginalNewNtCreateProcessEx
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\lw8172\documents\github\hooktestbed\wdmdrivertest\wdmdrivertest\hookhelper.cpp
;	COMDAT ?NewObReferenceObjectByHandle@@YGJPAXKPAU_OBJECT_TYPE@@DPAPAXPAU_OBJECT_HANDLE_INFORMATION@@@Z
_TEXT	SEGMENT
_status$ = -4						; size = 4
_Handle$ = 8						; size = 4
_DesiredAccess$ = 12					; size = 4
_ObjectType$ = 16					; size = 4
_AccessMode$ = 20					; size = 1
_Object$ = 24						; size = 4
_HandleInformation$ = 28				; size = 4
?NewObReferenceObjectByHandle@@YGJPAXKPAU_OBJECT_TYPE@@DPAPAXPAU_OBJECT_HANDLE_INFORMATION@@@Z PROC ; NewObReferenceObjectByHandle, COMDAT

; 47   : {

	npad	2
	push	ebp
	mov	ebp, esp
	push	ecx

; 48   : 	//KdPrint(("[%s] <----------------------\n", __FUNCTION__));  
; 49   : 	NTSTATUS status;
; 50   : 	status = OriginalObReferenceObjectByHandle(Handle,
; 51   : 			DesiredAccess,
; 52   : 			ObjectType,
; 53   : 			AccessMode,
; 54   : 			Object,
; 55   : 			HandleInformation
; 56   : 		);

	mov	eax, DWORD PTR _HandleInformation$[ebp]
	push	eax
	mov	ecx, DWORD PTR _Object$[ebp]
	push	ecx
	movzx	edx, BYTE PTR _AccessMode$[ebp]
	push	edx
	mov	eax, DWORD PTR _ObjectType$[ebp]
	push	eax
	mov	ecx, DWORD PTR _DesiredAccess$[ebp]
	push	ecx
	mov	edx, DWORD PTR _Handle$[ebp]
	push	edx
	call	?OriginalObReferenceObjectByHandle@@YGJPAXKPAU_OBJECT_TYPE@@DPAPAXPAU_OBJECT_HANDLE_INFORMATION@@@Z ; OriginalObReferenceObjectByHandle
	mov	DWORD PTR _status$[ebp], eax

; 57   : 
; 58   : 	if((status==STATUS_SUCCESS)&&(DesiredAccess==1))

	cmp	DWORD PTR _status$[ebp], 0
	jne	SHORT $LN3@NewObRefer
	cmp	DWORD PTR _DesiredAccess$[ebp], 1
	jne	SHORT $LN3@NewObRefer

; 59   : 	{         
; 60   : 		if(ObjectType== *PsProcessType)

	mov	eax, DWORD PTR _PsProcessType
	mov	ecx, DWORD PTR _ObjectType$[ebp]
	cmp	ecx, DWORD PTR [eax]
	jne	SHORT $LN3@NewObRefer

; 61   : 		{  
; 62   : 			KdPrint(("[%s] , ProcessName: %s\n", __FUNCTION__, (char *)((ULONG)(*Object) + EPROCESS_NAME_OFFSET)));  

	mov	edx, DWORD PTR _Object$[ebp]
	mov	eax, DWORD PTR [edx]
	add	eax, 364				; 0000016cH
	push	eax
	push	OFFSET ??_C@_0BN@NDKJECNL@NewObReferenceObjectByHandle?$AA@FNODOBFM@
	push	OFFSET ??_C@_0BI@IHKBDNEF@?$FL?$CFs?$FN?5?0?5ProcessName?3?5?$CFs?6?$AA@FNODOBFM@
	call	_DbgPrint
	add	esp, 12					; 0000000cH

; 63   : 			if( _stricmp((char *)((ULONG)(*Object) + EPROCESS_NAME_OFFSET),"notepad.exe")==0) 

	push	OFFSET ??_C@_0M@ENKGKOKC@notepad?4exe?$AA@FNODOBFM@
	mov	ecx, DWORD PTR _Object$[ebp]
	mov	edx, DWORD PTR [ecx]
	add	edx, 364				; 0000016cH
	push	edx
	call	__stricmp
	add	esp, 8
	test	eax, eax
	jne	SHORT $LN3@NewObRefer

; 64   : 			{             
; 65   : 				return STATUS_ACCESS_DENIED;

	mov	eax, -1073741790			; c0000022H
	jmp	SHORT $LN4@NewObRefer
$LN3@NewObRefer:

; 66   : 			}  
; 67   : 		}   
; 68   : 	}  
; 69   : 	return status;

	mov	eax, DWORD PTR _status$[ebp]
$LN4@NewObRefer:

; 70   : }

	mov	esp, ebp
	pop	ebp
	ret	24					; 00000018H
?NewObReferenceObjectByHandle@@YGJPAXKPAU_OBJECT_TYPE@@DPAPAXPAU_OBJECT_HANDLE_INFORMATION@@@Z ENDP ; NewObReferenceObjectByHandle
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\lw8172\documents\github\hooktestbed\wdmdrivertest\wdmdrivertest\hookhelper.cpp
;	COMDAT ?OriginalObReferenceObjectByHandle@@YGJPAXKPAU_OBJECT_TYPE@@DPAPAXPAU_OBJECT_HANDLE_INFORMATION@@@Z
_TEXT	SEGMENT
_Handle$ = 8						; size = 4
_DesiredAccess$ = 12					; size = 4
_ObjectType$ = 16					; size = 4
_AccessMode$ = 20					; size = 1
_Object$ = 24						; size = 4
_HandleInformation$ = 28				; size = 4
?OriginalObReferenceObjectByHandle@@YGJPAXKPAU_OBJECT_TYPE@@DPAPAXPAU_OBJECT_HANDLE_INFORMATION@@@Z PROC ; OriginalObReferenceObjectByHandle, COMDAT

; 23   : #ifdef _X86_
; 24   : 	_asm     
; 25   : 	{         
; 26   : 		mov edi,edi

	mov	edi, edi

; 27   : 		push ebp

	push	ebp

; 28   : 		mov ebp,esp; //到此为 ObReferenceObjectByHandle 原来的前5个字节(windbg)

	mov	ebp, esp

; 29   : 		mov eax,ObReferenceObjectByHandle

	mov	eax, DWORD PTR __imp__ObReferenceObjectByHandle@24

; 30   : 		add eax,5

	add	eax, 5

; 31   : 		jmp eax                      

	jmp	eax
?OriginalObReferenceObjectByHandle@@YGJPAXKPAU_OBJECT_TYPE@@DPAPAXPAU_OBJECT_HANDLE_INFORMATION@@@Z ENDP ; OriginalObReferenceObjectByHandle
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\lw8172\documents\github\hooktestbed\wdmdrivertest\wdmdrivertest\utils.h
;	COMDAT ?FindSubString@@YGEPAU_UNICODE_STRING@@0@Z
_TEXT	SEGMENT
_index$ = -4						; size = 4
_String$ = 8						; size = 4
_SubString$ = 12					; size = 4
?FindSubString@@YGEPAU_UNICODE_STRING@@0@Z PROC		; FindSubString, COMDAT

; 59   : {

	npad	2
	push	ebp
	mov	ebp, esp
	push	ecx

; 60   : 	ULONG index;
; 61   : 
; 62   : 	//
; 63   : 	//  First, check to see if the strings are equal.
; 64   : 	//
; 65   : 
; 66   : 	if (RtlEqualUnicodeString( String, SubString, TRUE )) {

	push	1
	mov	eax, DWORD PTR _SubString$[ebp]
	push	eax
	mov	ecx, DWORD PTR _String$[ebp]
	push	ecx
	call	DWORD PTR __imp__RtlEqualUnicodeString@12
	movzx	edx, al
	test	edx, edx
	je	SHORT $LN5@FindSubStr

; 67   : 
; 68   : 		return TRUE;

	mov	al, 1
	jmp	SHORT $LN6@FindSubStr
$LN5@FindSubStr:

; 69   : 	}
; 70   : 
; 71   : 	//
; 72   : 	//  String and SubString aren't equal, so now see if SubString
; 73   : 	//  in in String any where.
; 74   : 	//
; 75   : 	for (index = 0;

	mov	DWORD PTR _index$[ebp], 0

; 76   : 		index + SubString->Length <= String->Length;

	jmp	SHORT $LN4@FindSubStr
$LN3@FindSubStr:

; 77   : 		index++) {

	mov	eax, DWORD PTR _index$[ebp]
	add	eax, 1
	mov	DWORD PTR _index$[ebp], eax
$LN4@FindSubStr:
	mov	ecx, DWORD PTR _SubString$[ebp]
	movzx	edx, WORD PTR [ecx]
	add	edx, DWORD PTR _index$[ebp]
	mov	eax, DWORD PTR _String$[ebp]
	movzx	ecx, WORD PTR [eax]
	cmp	edx, ecx
	ja	SHORT $LN2@FindSubStr

; 78   : 			if (_wcsnicmp(&(String->Buffer[index]),
; 79   : 				SubString->Buffer,
; 80   : 				SubString->Length) == 0) {

	mov	edx, DWORD PTR _SubString$[ebp]
	movzx	eax, WORD PTR [edx]
	push	eax
	mov	ecx, DWORD PTR _SubString$[ebp]
	mov	edx, DWORD PTR [ecx+4]
	push	edx
	mov	eax, DWORD PTR _String$[ebp]
	mov	ecx, DWORD PTR [eax+4]
	mov	edx, DWORD PTR _index$[ebp]
	lea	eax, DWORD PTR [ecx+edx*2]
	push	eax
	call	__wcsnicmp
	add	esp, 12					; 0000000cH
	test	eax, eax
	jne	SHORT $LN1@FindSubStr

; 81   : 					//
; 82   : 					//  SubString is found in String, so return TRUE.
; 83   : 					//
; 84   : 					return TRUE;

	mov	al, 1
	jmp	SHORT $LN6@FindSubStr
$LN1@FindSubStr:

; 85   : 			}
; 86   : 	}

	jmp	SHORT $LN3@FindSubStr
$LN2@FindSubStr:

; 87   : 
; 88   : 	return FALSE;

	xor	al, al
$LN6@FindSubStr:

; 89   : }

	mov	esp, ebp
	pop	ebp
	ret	8
?FindSubString@@YGEPAU_UNICODE_STRING@@0@Z ENDP		; FindSubString
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\lw8172\documents\github\hooktestbed\wdmdrivertest\wdmdrivertest\utils.h
;	COMDAT ?PageOff@@YGXXZ
_TEXT	SEGMENT
?PageOff@@YGXXZ PROC					; PageOff, COMDAT

; 41   : {

	npad	2
	push	ebp
	mov	ebp, esp

; 42   : #ifdef _X86_
; 43   : 	__asm
; 44   : 	{
; 45   : 		cli ;//将处理器标志寄存器的中断标志位清0，不允许中断

	cli

; 46   : 		mov eax, cr0

	mov	eax, cr0

; 47   : 		and  eax, ~0x10000

	and	eax, -65537				; fffeffffH

; 48   : 		mov cr0, eax

	mov	cr0, eax

; 49   : 	}
; 50   : #endif 
; 51   : }

	pop	ebp
	ret	0
?PageOff@@YGXXZ ENDP					; PageOff
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\lw8172\documents\github\hooktestbed\wdmdrivertest\wdmdrivertest\utils.h
;	COMDAT ?PageOn@@YGXXZ
_TEXT	SEGMENT
?PageOn@@YGXXZ PROC					; PageOn, COMDAT

; 27   : {

	npad	2
	push	ebp
	mov	ebp, esp

; 28   : #ifdef _X86_
; 29   : 	__asm
; 30   : 	{
; 31   : 		mov  eax, cr0

	mov	eax, cr0

; 32   : 		or     eax, 0x10000

	or	eax, 65536				; 00010000H

; 33   : 		mov  cr0, eax

	mov	cr0, eax

; 34   : 		sti ;//将处理器标志寄存器的中断标志置1，允许中断

	sti

; 35   : 	}
; 36   : #endif 
; 37   : 	
; 38   : }

	pop	ebp
	ret	0
?PageOn@@YGXXZ ENDP					; PageOn
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\lw8172\documents\github\hooktestbed\wdmdrivertest\wdmdrivertest\hookhelper.cpp
;	COMDAT ?FindSpeCodeInMemory@HookHelper@@QAEJPAK0K@Z
_TEXT	SEGMENT
_uResult$ = -48						; size = 4
_this$ = -44						; size = 4
tv70 = -40						; size = 4
_bFind$1 = -36						; size = 4
_ntosknlEndAddr$ = -32					; size = 4
_ntosknlBase$ = -28					; size = 4
_uSzie$ = -24						; size = 4
_pBuf$ = -20						; size = 4
_module$ = -16						; size = 4
_i$2 = -12						; size = 4
_j$3 = -8						; size = 4
_status$ = -4						; size = 4
_pRet$ = 8						; size = 4
_code_sp_array$ = 12					; size = 4
_uCount$ = 16						; size = 4
?FindSpeCodeInMemory@HookHelper@@QAEJPAK0K@Z PROC	; HookHelper::FindSpeCodeInMemory, COMDAT
; _this$ = ecx

; 292  : {

	npad	2
	push	ebp
	mov	ebp, esp
	sub	esp, 48					; 00000030H
	push	esi
	mov	DWORD PTR _this$[ebp], ecx

; 293  : 	PAGED_CODE()

	call	DWORD PTR __imp__KeGetCurrentIrql@0
	movzx	eax, al
	cmp	eax, 1
	jle	SHORT $LN14@FindSpeCod
__annotation$16:
	int	44					; 0000002cH
	mov	DWORD PTR tv70[ebp], 0
	jmp	SHORT $LN15@FindSpeCod
$LN14@FindSpeCod:
	mov	DWORD PTR tv70[ebp], 1
$LN15@FindSpeCod:

; 294  : 
; 295  : 	NTSTATUS status = STATUS_UNSUCCESSFUL;

	mov	DWORD PTR _status$[ebp], -1073741823	; c0000001H

; 296  : 	ULONG uResult = -1;

	mov	DWORD PTR _uResult$[ebp], -1

; 297  : 	ULONG uSzie;
; 298  : 	ULONG ntosknlBase;
; 299  : 	ULONG ntosknlEndAddr;
; 300  : 	ULONG uMCount;
; 301  : 	PULONG pBuf;
; 302  : 
; 303  : 	PSYSTEM_MODULE_INFORMATION_ENTRY module;
; 304  : 
; 305  : 	ZwQuerySystemInformation(SystemModuleInformation, NULL, 0, &uSzie);

	lea	ecx, DWORD PTR _uSzie$[ebp]
	push	ecx
	push	0
	push	0
	push	11					; 0000000bH
	call	DWORD PTR __imp__ZwQuerySystemInformation@16

; 306  : 	if(NULL==(pBuf = (PULONG)ExAllocatePool(PagedPool, uSzie)))

	mov	edx, DWORD PTR _uSzie$[ebp]
	push	edx
	push	1
	call	DWORD PTR __imp__ExAllocatePool@8
	mov	DWORD PTR _pBuf$[ebp], eax
	cmp	DWORD PTR _pBuf$[ebp], 0
	jne	SHORT $LN11@FindSpeCod

; 307  : 	{
; 308  : 		KdPrint(("[%s] failed alloc memory failed \n", __FUNCTION__));

	push	OFFSET ??_C@_0CA@GHBGDHMM@HookHelper?3?3FindSpeCodeInMemory?$AA@FNODOBFM@
	push	OFFSET ??_C@_0CC@BKIIOGJF@?$FL?$CFs?$FN?5failed?5alloc?5memory?5failed?5@FNODOBFM@
	call	_DbgPrint
	add	esp, 8

; 309  : 		return status;

	mov	eax, DWORD PTR _status$[ebp]
	jmp	$LN12@FindSpeCod
$LN11@FindSpeCod:

; 310  : 	}
; 311  : 	KdPrint(("[%s] uSzie = %d \n", __FUNCTION__, uSzie));

	mov	eax, DWORD PTR _uSzie$[ebp]
	push	eax
	push	OFFSET ??_C@_0CA@GHBGDHMM@HookHelper?3?3FindSpeCodeInMemory?$AA@FNODOBFM@
	push	OFFSET ??_C@_0BC@OBFBDDCK@?$FL?$CFs?$FN?5uSzie?5?$DN?5?$CFd?5?6?$AA@FNODOBFM@
	call	_DbgPrint
	add	esp, 12					; 0000000cH

; 312  : 	status = ZwQuerySystemInformation(SystemModuleInformation,pBuf, uSzie, 0);

	push	0
	mov	ecx, DWORD PTR _uSzie$[ebp]
	push	ecx
	mov	edx, DWORD PTR _pBuf$[ebp]
	push	edx
	push	11					; 0000000bH
	call	DWORD PTR __imp__ZwQuerySystemInformation@16
	mov	DWORD PTR _status$[ebp], eax

; 313  : 	if(!NT_SUCCESS( status ))

	cmp	DWORD PTR _status$[ebp], 0
	jge	SHORT $LN10@FindSpeCod

; 314  : 	{
; 315  : 		KdPrint(("[%s] failed query \n", __FUNCTION__));

	push	OFFSET ??_C@_0CA@GHBGDHMM@HookHelper?3?3FindSpeCodeInMemory?$AA@FNODOBFM@
	push	OFFSET ??_C@_0BE@BMFCHCEB@?$FL?$CFs?$FN?5failed?5query?5?6?$AA@FNODOBFM@
	call	_DbgPrint
	add	esp, 8

; 316  : 		return status;

	mov	eax, DWORD PTR _status$[ebp]
	jmp	$LN12@FindSpeCod
$LN10@FindSpeCod:

; 317  : 	}
; 318  : 	module = (PSYSTEM_MODULE_INFORMATION_ENTRY)(( PULONG )pBuf + 1);

	mov	eax, DWORD PTR _pBuf$[ebp]
	add	eax, 4
	mov	DWORD PTR _module$[ebp], eax

; 319  : 
; 320  : 	ntosknlEndAddr=(ULONG)module->Base+(ULONG)module->Size;

	mov	ecx, DWORD PTR _module$[ebp]
	mov	edx, DWORD PTR [ecx+8]
	mov	eax, DWORD PTR _module$[ebp]
	add	edx, DWORD PTR [eax+12]
	mov	DWORD PTR _ntosknlEndAddr$[ebp], edx

; 321  : 	ntosknlBase=(ULONG)module->Base;

	mov	ecx, DWORD PTR _module$[ebp]
	mov	edx, DWORD PTR [ecx+8]
	mov	DWORD PTR _ntosknlBase$[ebp], edx

; 322  : 
; 323  : 	KdPrint(("[%s] Base:%08x, End:%08x ImageName:%s \n", __FUNCTION__, ntosknlBase, ntosknlEndAddr ,module->ImageName));

	mov	eax, DWORD PTR _module$[ebp]
	add	eax, 28					; 0000001cH
	push	eax
	mov	ecx, DWORD PTR _ntosknlEndAddr$[ebp]
	push	ecx
	mov	edx, DWORD PTR _ntosknlBase$[ebp]
	push	edx
	push	OFFSET ??_C@_0CA@GHBGDHMM@HookHelper?3?3FindSpeCodeInMemory?$AA@FNODOBFM@
	push	OFFSET ??_C@_0CI@PDKKEKCF@?$FL?$CFs?$FN?5Base?3?$CF08x?0?5End?3?$CF08x?5ImageNa@FNODOBFM@
	call	_DbgPrint
	add	esp, 20					; 00000014H

; 324  : 
; 325  : 	ExFreePool(pBuf);

	mov	eax, DWORD PTR _pBuf$[ebp]
	push	eax
	call	DWORD PTR __imp__ExFreePool@4

; 326  : 
; 327  : 	for (ULONG i = ntosknlBase;i < ntosknlEndAddr - (4 * uCount); i++)

	mov	ecx, DWORD PTR _ntosknlBase$[ebp]
	mov	DWORD PTR _i$2[ebp], ecx
	jmp	SHORT $LN9@FindSpeCod
$LN8@FindSpeCod:
	mov	edx, DWORD PTR _i$2[ebp]
	add	edx, 1
	mov	DWORD PTR _i$2[ebp], edx
$LN9@FindSpeCod:
	mov	eax, DWORD PTR _uCount$[ebp]
	shl	eax, 2
	mov	ecx, DWORD PTR _ntosknlEndAddr$[ebp]
	sub	ecx, eax
	cmp	DWORD PTR _i$2[ebp], ecx
	jae	SHORT $LN7@FindSpeCod

; 328  : 	{
; 329  : 		BOOL bFind = TRUE;

	mov	DWORD PTR _bFind$1[ebp], 1

; 330  : 		for (int j = 0; j < uCount; j++)

	mov	DWORD PTR _j$3[ebp], 0
	jmp	SHORT $LN6@FindSpeCod
$LN5@FindSpeCod:
	mov	edx, DWORD PTR _j$3[ebp]
	add	edx, 1
	mov	DWORD PTR _j$3[ebp], edx
$LN6@FindSpeCod:
	mov	eax, DWORD PTR _j$3[ebp]
	cmp	eax, DWORD PTR _uCount$[ebp]
	jae	SHORT $LN4@FindSpeCod

; 331  : 		{
; 332  : 			if ((*((ULONG *)(i + j * 4)) == code_sp_array[j]))

	mov	ecx, DWORD PTR _j$3[ebp]
	mov	edx, DWORD PTR _i$2[ebp]
	mov	eax, DWORD PTR _j$3[ebp]
	mov	esi, DWORD PTR _code_sp_array$[ebp]
	mov	ecx, DWORD PTR [edx+ecx*4]
	cmp	ecx, DWORD PTR [esi+eax*4]
	jne	SHORT $LN3@FindSpeCod

; 333  : 			{
; 334  : 				continue;

	jmp	SHORT $LN5@FindSpeCod

; 335  : 			}
; 336  : 			else

	jmp	SHORT $LN2@FindSpeCod
$LN3@FindSpeCod:

; 337  : 			{
; 338  : 				bFind = FALSE;

	mov	DWORD PTR _bFind$1[ebp], 0

; 339  : 				break;

	jmp	SHORT $LN4@FindSpeCod
$LN2@FindSpeCod:

; 340  : 			}
; 341  : 		}

	jmp	SHORT $LN5@FindSpeCod
$LN4@FindSpeCod:

; 342  : 
; 343  : 		if (bFind)

	cmp	DWORD PTR _bFind$1[ebp], 0
	je	SHORT $LN1@FindSpeCod

; 344  : 		{
; 345  : 			(*pRet) = i;

	mov	edx, DWORD PTR _pRet$[ebp]
	mov	eax, DWORD PTR _i$2[ebp]
	mov	DWORD PTR [edx], eax

; 346  : 			KdPrint(("[%s] Find:%08x\n",__FUNCTION__, *pRet));

	mov	ecx, DWORD PTR _pRet$[ebp]
	mov	edx, DWORD PTR [ecx]
	push	edx
	push	OFFSET ??_C@_0CA@GHBGDHMM@HookHelper?3?3FindSpeCodeInMemory?$AA@FNODOBFM@
	push	OFFSET ??_C@_0BA@EGNDBCFN@?$FL?$CFs?$FN?5Find?3?$CF08x?6?$AA@FNODOBFM@
	call	_DbgPrint
	add	esp, 12					; 0000000cH

; 347  : 			status = STATUS_SUCCESS;

	mov	DWORD PTR _status$[ebp], 0

; 348  : 			return status;

	mov	eax, DWORD PTR _status$[ebp]
	jmp	SHORT $LN12@FindSpeCod
$LN1@FindSpeCod:

; 349  : 		}
; 350  : 	}

	jmp	$LN8@FindSpeCod
$LN7@FindSpeCod:

; 351  : 
; 352  : 	KdPrint(("[%s] UnFind . \n",__FUNCTION__));

	push	OFFSET ??_C@_0CA@GHBGDHMM@HookHelper?3?3FindSpeCodeInMemory?$AA@FNODOBFM@
	push	OFFSET ??_C@_0BA@FFJEGKCA@?$FL?$CFs?$FN?5UnFind?5?4?5?6?$AA@FNODOBFM@
	call	_DbgPrint
	add	esp, 8

; 353  : 
; 354  : 	return status;

	mov	eax, DWORD PTR _status$[ebp]
$LN12@FindSpeCod:

; 355  : }

	pop	esi
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?FindSpeCodeInMemory@HookHelper@@QAEJPAK0K@Z ENDP	; HookHelper::FindSpeCodeInMemory
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\lw8172\documents\github\hooktestbed\wdmdrivertest\wdmdrivertest\hookhelper.cpp
;	COMDAT ?UnHookNtCreateProcess@HookHelper@@QAEEXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
_Irql$ = -1						; size = 1
?UnHookNtCreateProcess@HookHelper@@QAEEXZ PROC		; HookHelper::UnHookNtCreateProcess, COMDAT
; _this$ = ecx

; 279  : {

	npad	2
	push	ebp
	mov	ebp, esp
	sub	esp, 8
	mov	DWORD PTR _this$[ebp], ecx

; 280  : 	KdPrint(("[%s] <----------------------\n", __FUNCTION__));  

	push	OFFSET ??_C@_0CC@EKOPFHFD@HookHelper?3?3UnHookNtCreateProces@FNODOBFM@
	push	OFFSET ??_C@_0BO@MNJPLLPD@?$FL?$CFs?$FN?5?$DM?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?6?$AA@FNODOBFM@
	call	_DbgPrint
	add	esp, 8

; 281  : 	KIRQL Irql;
; 282  : 	PageOff();

	call	?PageOff@@YGXXZ				; PageOff

; 283  : 	KeRaiseIrql(DISPATCH_LEVEL, &Irql);  //函数开头五个字节写JMP

	mov	cl, 2
	call	DWORD PTR __imp_@KfRaiseIrql@4
	mov	BYTE PTR _Irql$[ebp], al

; 284  : 	RtlCopyMemory((UCHAR *)g_FunNtCreateProcess,NtCreateProcessOriginalBytes,5);  

	mov	eax, DWORD PTR ?g_FunNtCreateProcess@@3P6GJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@ZA ; g_FunNtCreateProcess
	mov	ecx, DWORD PTR ?NtCreateProcessOriginalBytes@@3PAEA
	mov	DWORD PTR [eax], ecx
	mov	dl, BYTE PTR ?NtCreateProcessOriginalBytes@@3PAEA+4
	mov	BYTE PTR [eax+4], dl

; 285  : 	KeLowerIrql(Irql);

	mov	cl, BYTE PTR _Irql$[ebp]
	call	DWORD PTR __imp_@KfLowerIrql@4

; 286  : 	PageOn();

	call	?PageOn@@YGXXZ				; PageOn

; 287  : 
; 288  : 	return TRUE;

	mov	al, 1

; 289  : }

	mov	esp, ebp
	pop	ebp
	ret	0
?UnHookNtCreateProcess@HookHelper@@QAEEXZ ENDP		; HookHelper::UnHookNtCreateProcess
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\lw8172\documents\github\hooktestbed\wdmdrivertest\wdmdrivertest\hookhelper.cpp
;	COMDAT ?HookNtCreateProcess@HookHelper@@QAEEPAPAX@Z
_TEXT	SEGMENT
_strNtCreateProcess$ = -64				; size = 8
_this$ = -56						; size = 4
_uAddress$ = -52					; size = 4
_Irql$ = -45						; size = 1
_uSpecArray$ = -44					; size = 32
_JmpAddress$ = -12					; size = 5
__$ArrayPad$ = -4					; size = 4
_newFun$ = 8						; size = 4
?HookNtCreateProcess@HookHelper@@QAEEPAPAX@Z PROC	; HookHelper::HookNtCreateProcess, COMDAT
; _this$ = ecx

; 237  : {

	npad	2
	push	ebp
	mov	ebp, esp
	sub	esp, 64					; 00000040H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	DWORD PTR _this$[ebp], ecx

; 238  : 	KdPrint(("[%s] <----------------------\n", __FUNCTION__));  

	push	OFFSET ??_C@_0CA@DDCEFIIE@HookHelper?3?3HookNtCreateProcess?$AA@FNODOBFM@
	push	OFFSET ??_C@_0BO@MNJPLLPD@?$FL?$CFs?$FN?5?$DM?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?6?$AA@FNODOBFM@
	call	_DbgPrint
	add	esp, 8

; 239  : 	KIRQL Irql;
; 240  : 	ULONG  CR0VALUE;  
; 241  : 	UCHAR JmpAddress[5] = {0xE9,0,0,0,0};       //跳转到HOOK函数的地址

	mov	BYTE PTR _JmpAddress$[ebp], 233		; 000000e9H
	mov	BYTE PTR _JmpAddress$[ebp+1], 0
	mov	BYTE PTR _JmpAddress$[ebp+2], 0
	mov	BYTE PTR _JmpAddress$[ebp+3], 0
	mov	BYTE PTR _JmpAddress$[ebp+4], 0

; 242  : 	UNICODE_STRING strNtCreateProcess;
; 243  : 	ULONG uAddress = 0;

	mov	DWORD PTR _uAddress$[ebp], 0

; 244  : 
; 245  : 	RtlInitUnicodeString(&strNtCreateProcess, L"NtCreateUserProcess");

	push	OFFSET ??_C@_1CI@PBJJPAEM@?$AAN?$AAt?$AAC?$AAr?$AAe?$AAa?$AAt?$AAe?$AAU?$AAs?$AAe?$AAr?$AAP?$AAr?$AAo?$AAc?$AAe?$AAs?$AAs?$AA?$AA@FNODOBFM@
	lea	eax, DWORD PTR _strNtCreateProcess$[ebp]
	push	eax
	call	DWORD PTR __imp__RtlInitUnicodeString@8

; 246  : 
; 247  : 	//85890845 fffff9b0 890c458b fff9ac85 NtCreateUserProcess + 0x10的特征码
; 248  : 	ULONG uSpecArray[8] = {
; 249  : 		0x85890845, 0xfffff9b0, 0x890c458b, 0xfff9ac85,

	mov	DWORD PTR _uSpecArray$[ebp], -2054617019 ; 85890845H
	mov	DWORD PTR _uSpecArray$[ebp+4], -1616	; fffff9b0H
	mov	DWORD PTR _uSpecArray$[ebp+8], -1995684469 ; 890c458bH
	mov	DWORD PTR _uSpecArray$[ebp+12], -414587	; fff9ac85H

; 250  : 		0x185d8bff, 0xf9a09d89, 0x458bffff, 0x8c85891c};

	mov	DWORD PTR _uSpecArray$[ebp+16], 408783871 ; 185d8bffH
	mov	DWORD PTR _uSpecArray$[ebp+20], -106914423 ; f9a09d89H
	mov	DWORD PTR _uSpecArray$[ebp+24], 1166802943 ; 458bffffH
	mov	DWORD PTR _uSpecArray$[ebp+28], -1937405668 ; 8c85891cH

; 251  : 	FindSpeCodeInMemory(&uAddress, uSpecArray, 8 );

	push	8
	lea	ecx, DWORD PTR _uSpecArray$[ebp]
	push	ecx
	lea	edx, DWORD PTR _uAddress$[ebp]
	push	edx
	mov	ecx, DWORD PTR _this$[ebp]
	call	?FindSpeCodeInMemory@HookHelper@@QAEJPAK0K@Z ; HookHelper::FindSpeCodeInMemory

; 252  : 	uAddress -= 0x10;

	mov	eax, DWORD PTR _uAddress$[ebp]
	sub	eax, 16					; 00000010H
	mov	DWORD PTR _uAddress$[ebp], eax

; 253  : 
; 254  : 	g_FunNtCreateProcess = (FunNtCreateUserProcessEx) uAddress;

	mov	ecx, DWORD PTR _uAddress$[ebp]
	mov	DWORD PTR ?g_FunNtCreateProcess@@3P6GJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@ZA, ecx ; g_FunNtCreateProcess

; 255  : 	if (!g_FunNtCreateProcess)

	cmp	DWORD PTR ?g_FunNtCreateProcess@@3P6GJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@ZA, 0 ; g_FunNtCreateProcess
	jne	SHORT $LN1@HookNtCrea

; 256  : 	{
; 257  : 		RtlCopyMemory(NtCreateProcessOriginalBytes, g_FunNtCreateProcess, 5);

	mov	edx, DWORD PTR ?g_FunNtCreateProcess@@3P6GJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@ZA ; g_FunNtCreateProcess
	mov	eax, DWORD PTR [edx]
	mov	DWORD PTR ?NtCreateProcessOriginalBytes@@3PAEA, eax
	mov	cl, BYTE PTR [edx+4]
	mov	BYTE PTR ?NtCreateProcessOriginalBytes@@3PAEA+4, cl

; 258  : 		KdPrint(("[%s] g_FunNtCreateProcess == NULL !!!!!\n", __FUNCTION__)); 

	push	OFFSET ??_C@_0CA@DDCEFIIE@HookHelper?3?3HookNtCreateProcess?$AA@FNODOBFM@
	push	OFFSET ??_C@_0CJ@IPJOHLF@?$FL?$CFs?$FN?5g_FunNtCreateProcess?5?$DN?$DN?5NUL@FNODOBFM@
	call	_DbgPrint
	add	esp, 8

; 259  : 		return FALSE;

	xor	al, al
	jmp	$LN2@HookNtCrea
$LN1@HookNtCrea:

; 260  : 	}
; 261  : 	RtlCopyMemory(NtCreateProcessOriginalBytes, g_FunNtCreateProcess, 5);

	mov	edx, DWORD PTR ?g_FunNtCreateProcess@@3P6GJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@ZA ; g_FunNtCreateProcess
	mov	eax, DWORD PTR [edx]
	mov	DWORD PTR ?NtCreateProcessOriginalBytes@@3PAEA, eax
	mov	cl, BYTE PTR [edx+4]
	mov	BYTE PTR ?NtCreateProcessOriginalBytes@@3PAEA+4, cl

; 262  : 	*(ULONG  *)(JmpAddress+1)=(ULONG)NewNtCreateProcessEx - ((ULONG)g_FunNtCreateProcess + 5);

	mov	edx, DWORD PTR ?g_FunNtCreateProcess@@3P6GJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@ZA ; g_FunNtCreateProcess
	add	edx, 5
	mov	eax, OFFSET ?NewNtCreateProcessEx@@YGJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@Z ; NewNtCreateProcessEx
	sub	eax, edx
	mov	DWORD PTR _JmpAddress$[ebp+1], eax

; 263  : 	KdPrint(("[NtCreateProcess] :0x%x",g_FunNtCreateProcess));

	mov	ecx, DWORD PTR ?g_FunNtCreateProcess@@3P6GJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@ZA ; g_FunNtCreateProcess
	push	ecx
	push	OFFSET ??_C@_0BI@CHNNDCKM@?$FLNtCreateProcess?$FN?5?30x?$CFx?$AA@FNODOBFM@
	call	_DbgPrint
	add	esp, 8

; 264  : 
; 265  : 
; 266  : 	PageOff();

	call	?PageOff@@YGXXZ				; PageOff

; 267  : 	KeRaiseIrql(DISPATCH_LEVEL, &Irql);  

	mov	cl, 2
	call	DWORD PTR __imp_@KfRaiseIrql@4
	mov	BYTE PTR _Irql$[ebp], al

; 268  : 	RtlCopyMemory((UCHAR *)g_FunNtCreateProcess,JmpAddress,5);  

	mov	edx, DWORD PTR ?g_FunNtCreateProcess@@3P6GJPAPAX0PAX11111PAU_RTL_USER_PROCESS_PARAMETERS@@11@ZA ; g_FunNtCreateProcess
	mov	eax, DWORD PTR _JmpAddress$[ebp]
	mov	DWORD PTR [edx], eax
	mov	cl, BYTE PTR _JmpAddress$[ebp+4]
	mov	BYTE PTR [edx+4], cl

; 269  : 	KeLowerIrql(Irql);

	mov	cl, BYTE PTR _Irql$[ebp]
	call	DWORD PTR __imp_@KfLowerIrql@4

; 270  : 	PageOn();

	call	?PageOn@@YGXXZ				; PageOn

; 271  : 
; 272  : 	m_bHookZwCreUserProcSuccess = TRUE;

	mov	edx, DWORD PTR _this$[ebp]
	mov	BYTE PTR [edx+1], 1

; 273  : 
; 274  : 	KdPrint(("[%s] ---------------------> \n", __FUNCTION__));  

	push	OFFSET ??_C@_0CA@DDCEFIIE@HookHelper?3?3HookNtCreateProcess?$AA@FNODOBFM@
	push	OFFSET ??_C@_0BO@HKHHGHLB@?$FL?$CFs?$FN?5?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?$DO?5?6?$AA@FNODOBFM@
	call	_DbgPrint
	add	esp, 8

; 275  : 	return TRUE;

	mov	al, 1
$LN2@HookNtCrea:

; 276  : }

	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	mov	esp, ebp
	pop	ebp
	ret	4
?HookNtCreateProcess@HookHelper@@QAEEPAPAX@Z ENDP	; HookHelper::HookNtCreateProcess
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\lw8172\documents\github\hooktestbed\wdmdrivertest\wdmdrivertest\hookhelper.cpp
;	COMDAT ?UnHookObReferenceObjectByHandle@HookHelper@@QAEEXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
_Irql$ = -1						; size = 1
?UnHookObReferenceObjectByHandle@HookHelper@@QAEEXZ PROC ; HookHelper::UnHookObReferenceObjectByHandle, COMDAT
; _this$ = ecx

; 224  : {

	npad	2
	push	ebp
	mov	ebp, esp
	sub	esp, 8
	mov	DWORD PTR _this$[ebp], ecx

; 225  : 	KdPrint(("[%s] <----------------------\n", __FUNCTION__));  

	push	OFFSET ??_C@_0CM@HAAJIBHO@HookHelper?3?3UnHookObReferenceObj@FNODOBFM@
	push	OFFSET ??_C@_0BO@MNJPLLPD@?$FL?$CFs?$FN?5?$DM?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?6?$AA@FNODOBFM@
	call	_DbgPrint
	add	esp, 8

; 226  : 	KIRQL Irql;
; 227  : 	PageOff();

	call	?PageOff@@YGXXZ				; PageOff

; 228  : 	KeRaiseIrql(DISPATCH_LEVEL, &Irql); //函数开头五个字节写JMP

	mov	cl, 2
	call	DWORD PTR __imp_@KfRaiseIrql@4
	mov	BYTE PTR _Irql$[ebp], al

; 229  : 	RtlCopyMemory((UCHAR *)ObReferenceObjectByHandle,ObReferenceObjectByHandleOriginalBytes,5);  

	mov	eax, DWORD PTR __imp__ObReferenceObjectByHandle@24
	mov	ecx, DWORD PTR ?ObReferenceObjectByHandleOriginalBytes@@3PAEA
	mov	DWORD PTR [eax], ecx
	mov	dl, BYTE PTR ?ObReferenceObjectByHandleOriginalBytes@@3PAEA+4
	mov	BYTE PTR [eax+4], dl

; 230  : 	KeLowerIrql(Irql);

	mov	cl, BYTE PTR _Irql$[ebp]
	call	DWORD PTR __imp_@KfLowerIrql@4

; 231  : 	PageOn();

	call	?PageOn@@YGXXZ				; PageOn

; 232  : 
; 233  : 	return TRUE;

	mov	al, 1

; 234  : }

	mov	esp, ebp
	pop	ebp
	ret	0
?UnHookObReferenceObjectByHandle@HookHelper@@QAEEXZ ENDP ; HookHelper::UnHookObReferenceObjectByHandle
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\lw8172\documents\github\hooktestbed\wdmdrivertest\wdmdrivertest\hookhelper.cpp
;	COMDAT ?HookObReferenceObjectByHandle@HookHelper@@QAEEPAPAX@Z
_TEXT	SEGMENT
_this$ = -20						; size = 4
_Irql$ = -13						; size = 1
_JmpAddress$ = -12					; size = 5
__$ArrayPad$ = -4					; size = 4
_newFun$ = 8						; size = 4
?HookObReferenceObjectByHandle@HookHelper@@QAEEPAPAX@Z PROC ; HookHelper::HookObReferenceObjectByHandle, COMDAT
; _this$ = ecx

; 199  : {

	npad	2
	push	ebp
	mov	ebp, esp
	sub	esp, 20					; 00000014H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	DWORD PTR _this$[ebp], ecx

; 200  : 	KdPrint(("[%s] <----------------------\n", __FUNCTION__));  

	push	OFFSET ??_C@_0CK@EMEBBEAG@HookHelper?3?3HookObReferenceObjec@FNODOBFM@
	push	OFFSET ??_C@_0BO@MNJPLLPD@?$FL?$CFs?$FN?5?$DM?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?6?$AA@FNODOBFM@
	call	_DbgPrint
	add	esp, 8

; 201  : 	KIRQL Irql;
; 202  : 	ULONG  CR0VALUE;  
; 203  : 	UCHAR JmpAddress[5] = {0xE9,0,0,0,0};       //跳转到HOOK函数的地址

	mov	BYTE PTR _JmpAddress$[ebp], 233		; 000000e9H
	mov	BYTE PTR _JmpAddress$[ebp+1], 0
	mov	BYTE PTR _JmpAddress$[ebp+2], 0
	mov	BYTE PTR _JmpAddress$[ebp+3], 0
	mov	BYTE PTR _JmpAddress$[ebp+4], 0

; 204  : 
; 205  : 	RtlCopyMemory(ObReferenceObjectByHandleOriginalBytes, ObReferenceObjectByHandle, 5);

	mov	eax, DWORD PTR __imp__ObReferenceObjectByHandle@24
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR ?ObReferenceObjectByHandleOriginalBytes@@3PAEA, ecx
	mov	dl, BYTE PTR [eax+4]
	mov	BYTE PTR ?ObReferenceObjectByHandleOriginalBytes@@3PAEA+4, dl

; 206  : 	*(ULONG  *)(JmpAddress+1)=(ULONG)NewObReferenceObjectByHandle - ((ULONG)ObReferenceObjectByHandle+5);

	mov	eax, DWORD PTR __imp__ObReferenceObjectByHandle@24
	add	eax, 5
	mov	ecx, OFFSET ?NewObReferenceObjectByHandle@@YGJPAXKPAU_OBJECT_TYPE@@DPAPAXPAU_OBJECT_HANDLE_INFORMATION@@@Z ; NewObReferenceObjectByHandle
	sub	ecx, eax
	mov	DWORD PTR _JmpAddress$[ebp+1], ecx

; 207  : 	KdPrint(("[ObReferenceObjectByHandle] :0x%x",ObReferenceObjectByHandle));

	mov	edx, DWORD PTR __imp__ObReferenceObjectByHandle@24
	push	edx
	push	OFFSET ??_C@_0CC@GLBJJFCJ@?$FLObReferenceObjectByHandle?$FN?5?30x?$CF@FNODOBFM@
	call	_DbgPrint
	add	esp, 8

; 208  : 
; 209  : 	
; 210  : 	PageOff();

	call	?PageOff@@YGXXZ				; PageOff

; 211  : 	KeRaiseIrql(DISPATCH_LEVEL, &Irql);  //函数开头五个字节写JMP

	mov	cl, 2
	call	DWORD PTR __imp_@KfRaiseIrql@4
	mov	BYTE PTR _Irql$[ebp], al

; 212  : 	RtlCopyMemory((UCHAR *)ObReferenceObjectByHandle,JmpAddress,5);  

	mov	eax, DWORD PTR __imp__ObReferenceObjectByHandle@24
	mov	ecx, DWORD PTR _JmpAddress$[ebp]
	mov	DWORD PTR [eax], ecx
	mov	dl, BYTE PTR _JmpAddress$[ebp+4]
	mov	BYTE PTR [eax+4], dl

; 213  : 	KeLowerIrql(Irql);

	mov	cl, BYTE PTR _Irql$[ebp]
	call	DWORD PTR __imp_@KfLowerIrql@4

; 214  : 	PageOn();

	call	?PageOn@@YGXXZ				; PageOn

; 215  : 
; 216  : 	KdPrint(("[%s] ---------------------> \n", __FUNCTION__));  

	push	OFFSET ??_C@_0CK@EMEBBEAG@HookHelper?3?3HookObReferenceObjec@FNODOBFM@
	push	OFFSET ??_C@_0BO@HKHHGHLB@?$FL?$CFs?$FN?5?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?$DO?5?6?$AA@FNODOBFM@
	call	_DbgPrint
	add	esp, 8

; 217  : 
; 218  : 	m_bHookObSuccess = TRUE;

	mov	eax, DWORD PTR _this$[ebp]
	mov	BYTE PTR [eax], 1

; 219  : 
; 220  : 	return FALSE;

	xor	al, al

; 221  : }

	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	mov	esp, ebp
	pop	ebp
	ret	4
?HookObReferenceObjectByHandle@HookHelper@@QAEEPAPAX@Z ENDP ; HookHelper::HookObReferenceObjectByHandle
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\lw8172\documents\github\hooktestbed\wdmdrivertest\wdmdrivertest\hookhelper.cpp
;	COMDAT ??1HookHelper@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??1HookHelper@@QAE@XZ PROC				; HookHelper::~HookHelper, COMDAT
; _this$ = ecx

; 183  : {

	npad	2
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 184  : 	//UnHookObReferenceObjectByHandle();
; 185  : 	if (m_bHookObSuccess)

	mov	eax, DWORD PTR _this$[ebp]
	movzx	ecx, BYTE PTR [eax]
	test	ecx, ecx
	je	SHORT $LN2@HookHelper

; 186  : 	{
; 187  : 		UnHookObReferenceObjectByHandle();

	mov	ecx, DWORD PTR _this$[ebp]
	call	?UnHookObReferenceObjectByHandle@HookHelper@@QAEEXZ ; HookHelper::UnHookObReferenceObjectByHandle
$LN2@HookHelper:

; 188  : 	}
; 189  : 
; 190  : 	if (m_bHookZwCreUserProcSuccess)

	mov	edx, DWORD PTR _this$[ebp]
	movzx	eax, BYTE PTR [edx+1]
	test	eax, eax
	je	SHORT $LN1@HookHelper

; 191  : 	{
; 192  : 		UnHookNtCreateProcess();

	mov	ecx, DWORD PTR _this$[ebp]
	call	?UnHookNtCreateProcess@HookHelper@@QAEEXZ ; HookHelper::UnHookNtCreateProcess
$LN1@HookHelper:

; 193  : 	}
; 194  : 	
; 195  : 	KdPrint(("[%s] <----------------------\n", __FUNCTION__));  

	push	OFFSET ??_C@_0BI@HFJKMNDA@HookHelper?3?3?$HOHookHelper?$AA@FNODOBFM@
	push	OFFSET ??_C@_0BO@MNJPLLPD@?$FL?$CFs?$FN?5?$DM?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?6?$AA@FNODOBFM@
	call	_DbgPrint
	add	esp, 8

; 196  : }

	mov	esp, ebp
	pop	ebp
	ret	0
??1HookHelper@@QAE@XZ ENDP				; HookHelper::~HookHelper
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\lw8172\documents\github\hooktestbed\wdmdrivertest\wdmdrivertest\hookhelper.cpp
;	COMDAT ??0HookHelper@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0HookHelper@@QAE@XZ PROC				; HookHelper::HookHelper, COMDAT
; _this$ = ecx

; 175  : {

	npad	2
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 176  : 	KdPrint(("[%s] <----------------------\n", __FUNCTION__));

	push	OFFSET ??_C@_0BH@OKKHHBGM@HookHelper?3?3HookHelper?$AA@FNODOBFM@
	push	OFFSET ??_C@_0BO@MNJPLLPD@?$FL?$CFs?$FN?5?$DM?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?6?$AA@FNODOBFM@
	call	_DbgPrint
	add	esp, 8

; 177  : 	m_bHookObSuccess = FALSE;

	mov	eax, DWORD PTR _this$[ebp]
	mov	BYTE PTR [eax], 0

; 178  : 	m_bHookZwCreUserProcSuccess = FALSE;

	mov	ecx, DWORD PTR _this$[ebp]
	mov	BYTE PTR [ecx+1], 0

; 179  : }

	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0HookHelper@@QAE@XZ ENDP				; HookHelper::HookHelper
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\lw8172\documents\github\hooktestbed\wdmdrivertest\wdmdrivertest\utils.h
;	COMDAT ??3@YAXPAX@Z
_TEXT	SEGMENT
_pointer$ = 8						; size = 4
??3@YAXPAX@Z PROC					; operator delete, COMDAT

; 22   : {

	npad	2
	push	ebp
	mov	ebp, esp

; 23   : 	ExFreePool(pointer);

	mov	eax, DWORD PTR _pointer$[ebp]
	push	eax
	call	DWORD PTR __imp__ExFreePool@4

; 24   : }

	pop	ebp
	ret	0
??3@YAXPAX@Z ENDP					; operator delete
_TEXT	ENDS
END
