; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.50727.1 

	TITLE	C:\Users\lw8172\Documents\GitHub\HookTestBed\WDMDriverTest\WDMDriverTest\Utils.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	??3@YAXPAX@Z					; operator delete
EXTRN	__imp__ExFreePool@4:PROC
; Function compile flags: /Odtp
; File c:\users\lw8172\documents\github\hooktestbed\wdmdrivertest\wdmdrivertest\utils.h
;	COMDAT ??3@YAXPAX@Z
_TEXT	SEGMENT
_pointer$ = 8						; size = 4
??3@YAXPAX@Z PROC					; operator delete, COMDAT

; 22   : {

	npad	2
	push	ebp
	mov	ebp, esp

; 23   : 	ExFreePool(pointer);

	mov	eax, DWORD PTR _pointer$[ebp]
	push	eax
	call	DWORD PTR __imp__ExFreePool@4

; 24   : }

	pop	ebp
	ret	0
??3@YAXPAX@Z ENDP					; operator delete
_TEXT	ENDS
END
